name: Terraform + ECS Deployment

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPO: my-app
  ECS_CLUSTER: my-ecs-cluster
  ECS_SERVICE: my-ecs-service
  TASK_FAMILY: my-task
  CONTAINER_NAME: my-container

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout source code

    - name: Checkout repository
      uses: actions/checkout@v3

    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Terraform setup

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      working-directory: terraform
      run: terraform init -backend-config=../config_env/dev/backend.tfvars

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve

    - name: Get Terraform ECR URI
      working-directory: terraform
      run: |
        erraform output -json > tf_output.json
        ECR_URI=$(jq -r '.repository_url.value' tf_output.json)
        echo "ECR_URI=$ECR_URI" >> $GITHUB_ENV
    
    - name: Verify ECR URI
      run: |
        echo "Resolved ECR_URI => $ECR_URI"

    # Login to Amazon ECR

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Build & Push Docker Image

    - name: Build and Push Docker Image
      run: |
        IMAGE_TAG=${GITHUB_SHA::7}
        echo "Using ECR URI: $ECR_URI"

        # Build Docker image (local name doesn't matter much)
        #docker build -t my-app:$IMAGE_TAG app/
        docker build -t $ECR_URI:$IMAGE_TAG app/

        # Tag it with Terraform-provided ECR URI
        #docker tag my-app:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
        docker push $ECR_URI:$IMAGE_TAG

        # Also push as latest
        docker tag $ECR_URI:$IMAGE_TAG $ECR_URI:latest
        docker push $ECR_URI:latest



        